### ISSUE TITLE
Remaining issue on AGAT 1st meeting Report

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-samples-un#32]
From @manuel489 

***Comments on AGAT 1st meeting Report:***
- I set `meeting-report` as doctype.
- This doc doesn't have a summary, yet the title "Summary" is still shown in the front page of the generated file.

*Screenshot (generated front page):*
![generated-title](https://user-images.githubusercontent.com/33627611/79814078-5c25fa00-834b-11ea-9d08-f49f2468fd85.PNG)

Originally posted https://github.com/metanorma/mn-samples-un/pull/31

**Comment by ronaldtse** [comment]
@manuel489 please help verify once https://github.com/metanorma/metanorma-un/issues/55 is fixed. Thanks!

**Comment by manuelfuenmayor** [comment]
I have checked at the date of this post and it is not fixed yet. Maybe in the next release.

**Comment by manuelfuenmayor** [comment]
Confirmed, issue is fixed now. Closing.
